//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNextComic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comics
    {
        public string Description { get; set; }
        public int Id { get; set; }
        public string Image { get; set; }
        public string Issue_Number { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Release_date { get; set; }
        public int Id_Comic { get; set; }
    }
}
