//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNextComic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preferences
    {
        public int UserID { get; set; }
        public int ItemID { get; set; }
        public double Value { get; set; }
        public int Id { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
